import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import { useLocation } from 'react-router-dom';
import { api } from '../../services/api';
import { LoadError } from '../../components/common/LoadError';
import { EmptyState } from '../../components/common/EmptyState';
import { ConfirmDialog } from '../../components/common/ConfirmDialog';
import { StatCard } from '../../components/common/StatCard';
import { ReceiptModal } from '../../components/common/ReceiptModal';
import { LayoutDashboard, Users, BedDouble, CreditCard, FileText, ShieldAlert, DoorOpen, Bell, BarChart3 } from 'lucide-react';

type Row = Record<string, any>;
const input = 'rounded-xl border border-slate-300 px-3 py-2 text-sm';
const button = 'rounded-xl bg-blue-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50';
const money = (n: any) => `₹${Number(n || 0).toLocaleString('en-IN')}`;
const date = (v: any) => v ? new Date(v).toLocaleString() : '—';

function useStaffData<T = any>(url: string) {
  const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  const reload = useCallback(async () => { setLoading(true); setError(''); try { setData(await api.get<T>(url)); } catch (e: any) { setError(e.message || 'Unable to load data.'); } finally { setLoading(false); } }, [url]);
  useEffect(() => { void reload(); }, [reload]); return { data, error, loading, reload, setData };
}

const Page: React.FC<React.PropsWithChildren<{title:string; description?:string; actions?:React.ReactNode}>> = ({title,description,actions,children}) => <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold text-slate-900">{title}</h1>{description&&<p className="mt-1 text-sm text-slate-600">{description}</p>}</div>{actions}</div>{children}</div>;
const Form: React.FC<React.PropsWithChildren<{onSubmit:(e:FormEvent<HTMLFormElement>)=>void; busy:boolean; submit:string}>> = ({onSubmit,busy,submit,children}) => <form onSubmit={onSubmit} className="flex flex-wrap items-end gap-3 rounded-2xl border border-slate-200 bg-white p-4">{children}<button className={button} disabled={busy}>{busy?'Saving…':submit}</button></form>;
const Field: React.FC<React.PropsWithChildren<{label:string}>> = ({label,children}) => <label className="flex min-w-40 flex-col gap-1 text-xs font-semibold text-slate-700">{label}{children}</label>;
const Table: React.FC<{headers:string[]; rows:React.ReactNode[][]; empty?:string}> = ({headers,rows,empty='No records found.'}) => <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white">{rows.length===0?<EmptyState title="No records" description={empty}/>:<table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-600"><tr>{headers.map(h=><th className="px-4 py-3" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-slate-100">{rows.map((r,i)=><tr key={i} className="align-top">{r.map((c,j)=><td className="px-4 py-3 text-slate-700" key={j}>{c}</td>)}</tr>)}</tbody></table>}</div>;
const ErrorBox:React.FC<{error:string}> = ({error}) => <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800">{error}</div>;
const actionBtn=(label:string,fn:()=>void,disabled=false)=> <button type="button" onClick={fn} disabled={disabled} className="mr-2 text-xs font-bold text-blue-800 underline disabled:opacity-40">{label}</button>;

export const StaffPage: React.FC = () => {
 const path=useLocation().pathname;
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[confirm,setConfirm]=useState<null|{title:string;message:string;run:()=>Promise<void>}>(null),[search,setSearch]=useState('');
 const [receipt,setReceipt]=useState<any>(null);
 const [appStatus,setAppStatus]=useState('ALL');
 const call=async (fn:()=>Promise<any>, reload?:()=>Promise<void>)=>{setBusy(true);setError('');setNotice('');try{const result=await fn();setNotice(result?.message||'Saved successfully.');await reload?.();return result;}catch(e:any){setError(e.message||'Request failed.');return null;}finally{setBusy(false);}};
 const confirmAction=(title:string,message:string,run:()=>Promise<void>)=>setConfirm({title,message,run});

 // Data sources are selected by the actual route. Every request maps to an existing backend route.
 const source = path==='/warden/applications'||path==='/admin/applications'?'/applications':path==='/warden/rooms'||path==='/admin/rooms'?'/rooms/summary':path==='/warden/outpasses'?'/outpasses':path==='/security/outpasses'?'/rooms/summary':path==='/warden/visitors'||path==='/security/visitors'||path==='/security/gate-console'?'/visitors/all':path==='/warden/curfew'||path==='/security/curfew'?'/curfew/records':path==='/warden/notices'||path==='/admin/notices'?'/notices':path==='/accounts/fee-heads'?'/fees/heads':path==='/accounts/defaulters'||path==='/warden/defaulters'?'/payments/defaulters':path==='/admin/users'?'/admin/users':path==='/admin/audit-logs'?'/admin/audit-logs':path==='/admin/settings'?'/curfew/config':path==='/reports'?'/reports/all':path==='/admin/dashboard'?'/admin/system-stats':path==='/warden/dashboard'?'/rooms/summary':path==='/accounts/dashboard'||path==='/warden/fees'?'/payments/all':'/rooms/summary';
 const {data,error:loadError,loading,reload}=useStaffData<any>(source);
 const mutate=async (endpoint:string,method:'post'|'put'|'delete',body?:any)=>call(()=>api[method](endpoint,body),reload);
 const qRows=(arr:any[])=>arr.filter(x=>!search||JSON.stringify(x).toLowerCase().includes(search.toLowerCase()));
 const searchBox=<input aria-label="Search records" placeholder="Search…" value={search} onChange={e=>setSearch(e.target.value)} className={input}/>;
 const body=(fn:(d:any)=>React.ReactNode)=>loading?<div className="rounded-xl bg-white p-8 text-sm text-slate-600">Loading…</div>:loadError?<LoadError message={loadError} onRetry={()=>void reload()}/>:data===null?<EmptyState title="No data" description="The backend did not return data for this section."/>:fn(data);

 const titleMap:Record<string,string>={'/warden/dashboard':'Warden Overview','/warden/applications':'Applications','/warden/rooms':'Rooms & Beds','/warden/outpasses':'Outpass Requests','/warden/curfew':'Curfew Records','/warden/notices':'Notice Board','/warden/visitors':'Visitor Logs','/warden/fees':'Fee Ledger','/warden/defaulters':'Defaulters','/accounts/dashboard':'Accounts Overview','/accounts/fee-heads':'Fee Heads & Dues','/accounts/defaulters':'Defaulters & Ledger','/security/gate-console':'Gate Console','/security/visitors':'Visitor Register','/security/curfew':'Curfew Gate Entries','/security/outpasses':'Outpass Gate Passes','/admin/dashboard':'Admin Dashboard','/admin/users':'User Management','/admin/settings':'Hostel & Curfew Rules','/admin/audit-logs':'Audit Logs','/admin/applications':'Applications','/admin/rooms':'Rooms & Beds','/admin/notices':'Notice Board','/reports':'Reports & Analytics'};
 const title=titleMap[path]||'Staff Portal';

 let content:React.ReactNode=null;
 if(path==='/warden/dashboard') content=body(d=><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Rooms" value={d.totalRooms} icon={BedDouble}/><StatCard title="Occupied beds" value={`${d.occupiedBeds}/${d.totalBeds}`} icon={Users}/><StatCard title="Available beds" value={d.availableBeds} icon={DoorOpen}/><StatCard title="Occupancy" value={`${d.occupancyRate}%`} icon={BarChart3}/><div className="sm:col-span-2 xl:col-span-4"><Table headers={['Block','Rooms','Occupied','Available','Occupancy']} rows={(d.blockStats||[]).map((b:any)=>[b.name,b.totalRooms,b.occupiedBeds,b.availableBeds,`${b.occupancyPercent}%`])}/></div></div>);
 if(path==='/accounts/dashboard'||path==='/warden/fees') { content=body(d=><><div className="grid gap-4 sm:grid-cols-3"><StatCard title="Collected" value={money(d.summary?.totalCollected)} icon={CreditCard}/><StatCard title="Pending" value={money(d.summary?.totalPending)} icon={FileText}/><StatCard title="Overdue" value={money(d.summary?.totalOverdue)} icon={ShieldAlert}/></div><div className="flex justify-end">{searchBox}</div><Table headers={['Student','Roll','Fee','Amount','Status','Due','Receipt']} rows={qRows(d.payments||[]).map((p:any)=>[p.student?.name,p.student?.rollNumber,p.feeHead?.name,money(p.amount),p.status,date(p.dueDate),p.receiptNumber?actionBtn(p.receiptNumber,()=>void call(async()=>{const x=await api.get(`/payments/receipt/${encodeURIComponent(p.receiptNumber)}`);setReceipt(x);return x})): '—'])}/></>); }
 if(path==='/accounts/defaulters'||path==='/warden/defaulters') { content=<>{body(d=><Table headers={['Student','Roll','Fee','Amount','Status','Due','Room']} rows={qRows(d||[]).map((p:any)=>[p.student?.name,p.student?.rollNumber,p.feeHead?.name,money(p.amount),p.status,date(p.dueDate),p.student?.allocations?.[0]?.room?.roomNumber||'—'])}/>)}</>; }
 if(path==='/warden/applications'||path==='/admin/applications') content=<><div className="flex flex-wrap gap-2">{searchBox}<select aria-label="Application status" className={input} value={appStatus} onChange={e=>setAppStatus(e.target.value)}>{['ALL','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','WITHDRAWN'].map(s=><option key={s}>{s}</option>)}</select></div>{body(d=><Table headers={['Application','Student','Course / Year','Medical info','Preference','Status','Document','Actions']} rows={qRows(d||[]).filter((a:any)=>appStatus==='ALL'||a.status===appStatus).map((a:any)=>[a.applicationNumber,<>{a.student?.name}<br/>{a.student?.rollNumber}<br/>{a.student?.email}</>,`${a.student?.course||'—'} / ${a.student?.year||'—'}`,a.student?.medicalInfo||'Not provided',a.roomTypePreference,<span className="font-semibold">{a.status}{a.rejectionReason?` — ${a.rejectionReason}`:''}</span>,a.supportingDoc?<a className="text-blue-800 underline" href={a.supportingDoc} target="_blank" rel="noreferrer">Open document</a>:'—',path==='/warden/applications'?<>{actionBtn('Review',()=>void mutate(`/applications/${a.id}/under-review`,'post',{}),a.status!=='SUBMITTED'||busy)} {actionBtn('Approve',()=>confirmAction('Approve application',`Approve ${a.applicationNumber}?`,async()=>{await mutate(`/applications/${a.id}/approve`,'post',{});setConfirm(null)}),a.status==='APPROVED'||a.status==='WITHDRAWN'||busy)} {actionBtn('Reject',()=>{const reason=window.prompt('Rejection reason (at least 5 characters):');if(reason&&window.confirm(`Reject ${a.applicationNumber} with this reason?`))void mutate(`/applications/${a.id}/reject`,'post',{reason})},a.status==='WITHDRAWN'||a.status==='APPROVED'||busy)}</>:null])}/>)}</>;
 if(path==='/warden/rooms'||path==='/admin/rooms') content=<RoomActions busy={busy} call={call} reload={reload}/>;
 if(path==='/warden/outpasses') content=<>{searchBox}{body(d=><Table headers={['Pass','Student','Type','Reason','Destination','Departure / Return','Status','Actions']} rows={qRows(d||[]).map((o:any)=>[o.outpassNumber,<>{o.student?.name}<br/>{o.student?.rollNumber}</>,o.type,o.reason,o.destination,<>{date(o.departureTime)}<br/>{date(o.expectedReturnTime)}</>,o.status,<>{actionBtn('Approve',()=>confirmAction('Approve outpass',`Approve ${o.outpassNumber}?`,async()=>{await mutate(`/outpasses/${o.id}/approve`,'post',{});setConfirm(null)}),o.status!=='PENDING'||busy)} {actionBtn('Reject',()=>{const reason=window.prompt('Rejection reason (at least 5 characters):');if(reason&&window.confirm(`Reject ${o.outpassNumber} with this reason?`))void mutate(`/outpasses/${o.id}/reject`,'post',{reason})},o.status!=='PENDING'||busy)}</>])}/>)}</>;
 if(path==='/warden/visitors'||path==='/security/visitors') content=<>{searchBox}<VisitorGate data={data} loading={loading} error={loadError} reload={reload} call={call} qRows={qRows} busy={busy}/></>;
 if(path==='/security/gate-console') content=<GateConsole call={call} busy={busy} reload={reload} visitors={data} loading={loading} loadError={loadError}/>;
 if(path==='/security/outpasses') content=<GateOutpass call={call} busy={busy}/>;
 if(path==='/warden/curfew'||path==='/security/curfew') content=<CurfewPage data={data} loading={loading} loadError={loadError} reload={reload} call={call} role={path.startsWith('/security')?'SECURITY':'WARDEN'} busy={busy}/>;
 if(path==='/admin/settings') content=<CurfewSettings data={data} call={call} busy={busy}/>;
 if(path==='/warden/notices'||path==='/admin/notices') content=<NoticePage data={data} loading={loading} error={loadError} reload={reload} call={call} busy={busy} qRows={qRows} searchBox={searchBox} confirmAction={confirmAction} setConfirm={setConfirm}/>;
 if(path==='/accounts/fee-heads') content=<FeeHeads data={data} loading={loading} error={loadError} reload={reload} call={call} busy={busy}/>;
 if(path==='/reports') content=body(d=><Report data={d}/>);
 if(path==='/admin/dashboard') content=body(d=><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard title="Users" value={d.users?.totalUsers} icon={Users}/><StatCard title="Students" value={d.users?.students} icon={Users}/><StatCard title="Active users" value={d.users?.activeUsers} icon={LayoutDashboard}/><StatCard title="Rooms" value={d.hostel?.totalRooms} icon={BedDouble}/><StatCard title="Occupied beds" value={`${d.hostel?.occupiedBeds}/${d.hostel?.totalBeds}`} icon={DoorOpen}/><StatCard title="Applications" value={d.hostel?.totalApplications} icon={FileText}/><StatCard title="Pending outpasses" value={d.hostel?.pendingOutpasses} icon={FileText}/><StatCard title="Visitors inside" value={d.hostel?.activeVisitors} icon={Users}/></div>);
 if(path==='/admin/users') content=<AdminUsers data={data} loading={loading} error={loadError} reload={reload} call={call} busy={busy} searchBox={searchBox} qRows={qRows}/>;
 if(path==='/admin/audit-logs') content=<>{searchBox}{body(d=><Table headers={['When','User','Role','Action','Module','Details','IP']} rows={qRows(d||[]).map((x:any)=>[date(x.createdAt),x.userName||'—',x.userRole||'—',x.action,x.module,x.details,x.ipAddress||'—'])}/>)}</>;
 if(!content) content=body(d=><>{title==='Staff Portal'?<EmptyState title="Unavailable" description="This staff capability is not exposed by the existing backend."/>:<></>}</>);
 return <Page title={title} description="Live data from the hostel management backend.">{error&&<ErrorBox error={error}/ >}{notice&&<div role="status" className="rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</div>}{content}<ReceiptModal isOpen={!!receipt} receiptData={receipt} onClose={()=>setReceipt(null)}/><ConfirmDialog isOpen={!!confirm} title={confirm?.title||''} message={confirm?.message||''} onClose={()=>setConfirm(null)} onConfirm={()=>void confirm?.run()} isLoading={busy} isDestructive/></Page>;
};

// Room summary and room list use different contracts, so load the list separately.
function RoomActions({busy,call,reload}:{busy:boolean;call:any;reload:any}) {
 const [rooms,setRooms]=useState<Row[]>([]),[blocks,setBlocks]=useState<Row[]>([]),[eligible,setEligible]=useState<Row[]>([]),[beds,setBeds]=useState<Row[]>([]),[roomForm,setRoomForm]=useState(false),[msg,setMsg]=useState(''),[selectedRoom,setSelectedRoom]=useState('');
 const [reallocRoom,setReallocRoom]=useState('');
 const load=useCallback(async()=>{try{const [r,b,e,ab]=await Promise.all([api.get<Row[]>('/rooms'),api.get<any>('/rooms/summary').then(x=>x.blockStats||[]),api.get<Row[]>('/allocations/eligible-students'),api.get<Row[]>('/rooms/available-beds')]);setRooms(r);setBlocks(b);setEligible(e);setBeds(ab);}catch(e:any){setMsg(e.message)}},[]);useEffect(()=>{void load()},[load]);
 return <section className="space-y-4"><div className="flex justify-between"><h2 className="text-lg font-bold">Bed allocation</h2><button className={button} onClick={()=>setRoomForm(!roomForm)}>Add room</button></div>{msg&&<ErrorBox error={msg}/ >}{roomForm&&<Form busy={busy} submit="Create room" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void call(()=>api.post('/rooms',{blockId:f.get('blockId'),floor:f.get('floor'),roomNumber:f.get('roomNumber'),capacity:f.get('capacity'),roomType:f.get('roomType')}),async()=>{await load();await reload();setRoomForm(false)})}}><Field label="Block"><select name="blockId" required className={input}>{blocks.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></Field><Field label="Floor"><input name="floor" type="number" min="1" required className={input}/></Field><Field label="Room number"><input name="roomNumber" required className={input}/></Field><Field label="Capacity"><input name="capacity" type="number" min="1" max="8" required className={input}/></Field><Field label="Room type"><select name="roomType" className={input}><option>Single AC</option><option>Double Non-AC</option><option>Triple Non-AC</option></select></Field></Form>}
 <Form busy={busy} submit="Allocate bed" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void call(()=>api.post('/allocations',{studentId:f.get('studentId'),roomId:f.get('roomId'),bedId:f.get('bedId'),applicationId:f.get('applicationId')||undefined}),load)}}><Field label="Approved student"><select name="studentId" required className={input}><option value="">Select student</option>{eligible.map(a=><option key={a.student.id} value={a.student.id}>{a.student.name} · {a.student.rollNumber} · {a.applicationNumber}</option>)}</select></Field><Field label="Room"><select name="roomId" required className={input} value={selectedRoom} onChange={e=>setSelectedRoom(e.target.value)}><option value="">Select room</option>{rooms.filter(r=>r.status==='AVAILABLE').map(r=><option key={r.id} value={r.id}>{r.roomNumber} · {r.block?.name}</option>)}</select></Field><Field label="Available bed"><select name="bedId" required className={input}><option value="">Select bed</option>{beds.filter(b=>!selectedRoom||String(b.roomId)===selectedRoom).map(b=><option key={b.id} value={b.id}>{b.room?.roomNumber} / {b.bedNumber} · {b.room?.block?.name}</option>)}</select></Field><Field label="Application ID (optional)"><input name="applicationId" type="number" className={input}/></Field></Form>
 <Form busy={busy} submit="Reallocate student" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void call(()=>api.post('/allocations/reallocate',{studentId:f.get('studentId'),newRoomId:f.get('newRoomId'),newBedId:f.get('newBedId'),reason:f.get('reason')}),load)}}><Field label="Currently allocated student"><select name="studentId" required className={input}><option value="">Select resident</option>{rooms.flatMap(r=>(r.beds||[]).flatMap((b:any)=>(b.allocations||[]).filter((a:any)=>a.status==='ACTIVE').map((a:any)=><option key={a.id} value={a.studentId}>{a.student?.name} · {a.student?.rollNumber} · {r.roomNumber}/{b.bedNumber}</option>)))}</select></Field><Field label="New room"><select name="newRoomId" required value={reallocRoom} onChange={e=>setReallocRoom(e.target.value)} className={input}><option value="">Select room</option>{rooms.filter(r=>r.status==='AVAILABLE').map(r=><option key={r.id} value={r.id}>{r.roomNumber} · {r.block?.name}</option>)}</select></Field><Field label="New bed"><select name="newBedId" required className={input}><option value="">Select bed</option>{beds.filter(b=>!reallocRoom||String(b.roomId)===reallocRoom).map(b=><option key={b.id} value={b.id}>{b.room?.roomNumber} / {b.bedNumber}</option>)}</select></Field><Field label="Reason"><input name="reason" className={input}/></Field></Form>
 <Table headers={['Room','Block','Floor','Type','Capacity','Beds and occupants','Status','Actions']} rows={rooms.map(r=>[r.roomNumber,r.block?.name,r.floor,r.roomType,r.capacity,<div>{(r.beds||[]).map((b:any)=><div key={b.id} className="text-xs">{b.bedNumber}: {b.allocations?.[0]?.student?.name|| (b.isOccupied?'Occupied':'Available')} {b.allocations?.[0]?.status==='ACTIVE'&&actionBtn('Vacate',()=>{if(confirm(`Vacate ${b.bedNumber} in ${r.roomNumber}?`))void call(()=>api.post(`/allocations/${b.allocations[0].id}/vacate`,{}),load)})}</div>)}</div>,r.status,<button disabled={(r.beds||[]).some((b:any)=>b.isOccupied)&&r.status!=='MAINTENANCE'} className="text-xs font-bold text-blue-800 underline disabled:opacity-40" onClick={()=>{if(confirm(`Change maintenance status for ${r.roomNumber}?`))void call(()=>api.put(`/rooms/${r.id}/maintenance`,{}),load)}}>{r.status==='MAINTENANCE'?'End maintenance':'Maintenance'}</button>])}/></section>;
}
function VisitorGate({data,loading,error,reload,call,qRows,busy}:any){return <div className="space-y-4">{!loading&&!error&&<Table headers={['Visitor','Host student','Contact','Purpose','Date / time','Status','Log','Actions']} rows={qRows(data||[]).map((v:any)=>[v.visitorName,<>{v.student?.name}<br/>{v.student?.rollNumber}</>,v.visitorContact,v.purpose,`${v.visitDate} ${v.expectedTime}`,v.isOverstay?'OVERSTAY':v.status,`${date(v.visitorLog?.entryTime)} / ${date(v.visitorLog?.exitTime)}`,v.status==='INSIDE'?actionBtn('Record exit',()=>call(()=>api.post(`/visitors/${v.id}/exit`,{}),reload),busy):null])}/>}<WalkIn call={call} reload={reload} busy={busy}/></div>}
function WalkIn({call,reload,busy}:{call:any;reload:any;busy:boolean}){return <details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">Register walk-in visitor</summary><Form busy={busy} submit="Register entry" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void call(()=>api.post('/visitors/walk-in',Object.fromEntries(f)),reload)}}><Field label="Student roll number"><input name="studentRoll" required className={input}/></Field><Field label="Visitor name"><input name="visitorName" required className={input}/></Field><Field label="Contact"><input name="visitorContact" required className={input}/></Field><Field label="Relationship"><input name="relationship" required className={input}/></Field><Field label="Purpose"><input name="purpose" required className={input}/></Field></Form></details>}
function GateConsole({call,busy,reload,visitors,loading,loadError}:any){const [id,setId]=useState(''),[otp,setOtp]=useState(''),[result,setResult]=useState(''),[generated,setGenerated]=useState('');return <div className="space-y-4"><Form busy={busy} submit="Verify visitor OTP" onSubmit={e=>{e.preventDefault();void call(async()=>{const r=await api.post('/visitors/verify-otp',{visitorRequestId:id,otp});setResult(r.message||'Entry verified');return r},reload)}}><Field label="Visitor request ID"><input required type="number" value={id} onChange={e=>setId(e.target.value)} className={input}/></Field><Field label="6-digit OTP"><input required minLength={6} maxLength={6} value={otp} onChange={e=>setOtp(e.target.value)} className={input}/></Field></Form>{loading?<p>Loading visitor requests…</p>:loadError?<LoadError message={loadError} onRetry={reload}/>:<Table headers={['Request ID','Visitor','Host','Visit date','Status','Actions']} rows={(visitors||[]).map((v:any)=>[v.id,v.visitorName,`${v.student?.name||'—'} · ${v.student?.rollNumber||'—'}`,`${v.visitDate} ${v.expectedTime}`,v.status,['PENDING','OTP_GENERATED','EXPIRED','DENIED'].includes(v.status)?actionBtn('Regenerate OTP',()=>void call(async()=>{const r=await api.post(`/visitors/${v.id}/generate-otp`,{});setId(String(v.id));setGenerated(r.otp);return r},reload),busy):'—'])}/>}<WalkIn call={call} reload={reload} busy={busy}/>{result&&<div role="status">{result}</div>}{generated&&<div role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm">Temporary demo OTP for request {id}: <strong>{generated}</strong></div>}</div>}
function GateOutpass({call,busy}:any){const [query,setQuery]=useState(''),[pass,setPass]=useState<Row|null>(null),[err,setErr]=useState('');return <div className="space-y-4"><Form busy={busy} submit="Find pass" onSubmit={async e=>{e.preventDefault();setErr('');try{setPass(await api.post('/outpasses/verify-gate',{query}))}catch(x:any){setErr(x.message)}}}><Field label="Outpass number or student roll"><input value={query} onChange={e=>setQuery(e.target.value)} required className={input}/></Field></Form>{err&&<ErrorBox error={err}/ >}{pass&&<div className="rounded-2xl border bg-white p-5"><h2 className="font-bold">{pass.outpassNumber} · {pass.student?.name}</h2><p>{pass.status} · {pass.destination} · Return by {date(pass.expectedReturnTime)}</p>{pass.status==='APPROVED'&&<button disabled={busy} className={`${button} mt-3`} onClick={()=>void call(()=>api.post(`/outpasses/${pass.id}/log-exit`,{})).then((r:any)=>r&&setPass(r.outpass))}>Log exit</button>}{['APPROVED','ACTIVE'].includes(pass.status)&&<button disabled={busy} className={`${button} ml-2 mt-3`} onClick={()=>void call(()=>api.post(`/outpasses/${pass.id}/log-return`,{})).then((r:any)=>r&&setPass(r.outpass))}>Log return</button>}</div>}</div>}
function CurfewPage({data,loading,loadError,reload,call,role,busy}:any){const [roll,setRoll]=useState(''),[onlyViolations,setOnlyViolations]=useState(false);return <div className="space-y-4">{role==='WARDEN'&&<CurfewRuleForm call={call}/>}<Form busy={busy} submit="Log gate entry" onSubmit={e=>{e.preventDefault();void call(()=>api.post('/curfew/log-entry',{studentRoll:roll}),reload)}}><Field label="Student roll number"><input required value={roll} onChange={e=>setRoll(e.target.value)} className={input}/></Field></Form><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={onlyViolations} onChange={e=>setOnlyViolations(e.target.checked)}/> Unwaived violations only</label>{loading?<p>Loading records…</p>:loadError?<LoadError message={loadError} onRetry={reload}/>:<Table headers={['Student','Roll','Entry','Curfew','Delay','Flag','Waived','Recorded by']} rows={(data?.records||[]).filter((r:any)=>!onlyViolations||(r.flaggedLate&&!r.isWaived)).map((r:any)=>[r.student?.name,r.student?.rollNumber,date(r.entryTime),r.curfewTime,`${r.delayMinutes} min`,r.flaggedLate?'Late':'On time',r.isWaived?r.waiveReason:'—',r.recordedBy])}/>}</div>}
function CurfewRuleForm({call}:any){const [config,setConfig]=useState<Row|null>(null),[err,setErr]=useState(''),[saved,setSaved]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{void api.get<Row>('/curfew/config').then(setConfig).catch((e:any)=>setErr(e.message))},[]);if(err)return <ErrorBox error={err}/>;if(!config)return <p>Loading curfew rules…</p>;return <div className="space-y-2 rounded-2xl border border-slate-200 bg-white p-4"><h2 className="font-bold">Curfew configuration</h2><Form busy={busy} submit="Update rules" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);void call(()=>api.put('/curfew/config',Object.fromEntries(f))).then((r:any)=>{if(r){setConfig(r);setSaved('Curfew rules updated.')}}).finally(()=>setBusy(false))}}>{[['weekdayCurfew','Weekday curfew'],['weekendCurfew','Weekend curfew'],['specialCurfew','Special curfew'],['permittedVisitorUntil','Visitor hours until']].map(([n,l])=><Field key={n} label={l}><input name={n} type="time" defaultValue={config[n]} required className={input}/></Field>)}</Form>{saved&&<p role="status" className="text-xs text-emerald-700">{saved}</p>}</div>}
function CurfewSettings({data,call,busy}:any){const [values,setValues]=useState<Row>({});useEffect(()=>{if(data)setValues({weekdayCurfew:data.weekdayCurfew,weekendCurfew:data.weekendCurfew,specialCurfew:data.specialCurfew,permittedVisitorUntil:data.permittedVisitorUntil})},[data]);return <Form busy={busy} submit="Save rules" onSubmit={e=>{e.preventDefault();void call(()=>api.put('/curfew/config',values))}}>{[['weekdayCurfew','Weekday curfew'],['weekendCurfew','Weekend curfew'],['specialCurfew','Special curfew'],['permittedVisitorUntil','Visitor hours until']].map(([n,l])=><Field key={n} label={l}><input name={n} type="time" value={values[n]||''} onChange={e=>setValues((v:Row)=>({...v,[n]:e.target.value}))} required className={input}/></Field>)}</Form>}
function FeeHeads({data,loading,error,reload,call,busy}:any){return <div className="space-y-4">{!loading&&!error&&<Table headers={['Fee','Amount','Term','Room category','Payments']} rows={(data||[]).map((h:any)=>[h.name,money(h.amount),h.term,h.roomCategory,h._count?.payments??0])}/>}<Form busy={busy} submit="Create fee head" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void call(()=>api.post('/fees/heads',{name:f.get('name'),amount:Number(f.get('amount')),term:f.get('term'),roomCategory:f.get('roomCategory')}),reload)}}><Field label="Name"><input name="name" required className={input}/></Field><Field label="Amount"><input name="amount" type="number" min="0.01" step="0.01" required className={input}/></Field><Field label="Term"><input name="term" required className={input}/></Field><Field label="Room category"><select name="roomCategory" className={input}><option>All</option><option>Single AC</option><option>Double Non-AC</option><option>Triple Non-AC</option></select></Field></Form><Form busy={busy} submit="Assign to residents" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!confirm('Assign this fee to all allocated students?'))return;void call(()=>api.post('/fees/assign',{feeHeadId:f.get('feeHeadId'),dueDate:f.get('dueDate')}),reload)}}><Field label="Fee head"><select name="feeHeadId" required className={input}>{(data||[]).map((h:any)=><option key={h.id} value={h.id}>{h.name} · {money(h.amount)}</option>)}</select></Field><Field label="Due date"><input type="date" name="dueDate" required className={input}/></Field></Form></div>}
function NoticePage({data,loading,error,reload,call,busy,qRows,searchBox,confirmAction,setConfirm}:any){const [edit,setEdit]=useState<Row|null>(null);return <div className="space-y-4">{searchBox}{!loading&&!error&&<Table headers={['Title','Category','Target','Urgent','Published','Expires','Author','Actions']} rows={qRows(data||[]).map((n:any)=>[n.title,n.category,n.target,n.isUrgent?'Yes':'No',date(n.publishedAt),date(n.expiresAt),n.author?.name,<>{actionBtn('Edit',()=>setEdit(n),busy)}{actionBtn('Delete',()=>confirmAction('Delete notice',`Delete “${n.title}”?`,async()=>{await call(()=>api.delete(`/notices/${n.id}`),reload);setConfirm(null)}),busy)}</>])}/>}<details className="rounded-2xl border bg-white p-4" open={!!edit}><summary className="cursor-pointer font-bold">{edit?'Edit notice':'Create notice'}</summary><Form busy={busy} submit={edit?'Save changes':'Publish notice'} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget),payload={title:f.get('title'),body:f.get('body'),category:f.get('category'),target:f.get('target'),isUrgent:f.get('isUrgent')==='on',expiresAt:f.get('expiresAt')||null,attachmentUrl:f.get('attachmentUrl')||null};void call(()=>edit?api.put(`/notices/${edit.id}`,payload):api.post('/notices',payload),async()=>{setEdit(null);await reload()})}}><Field label="Title"><input name="title" defaultValue={edit?.title} required className={input}/></Field><Field label="Category"><select name="category" defaultValue={edit?.category||'GENERAL'} className={input}>{['GENERAL','URGENT','EVENT','MAINTENANCE'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Target block"><input name="target" defaultValue={edit?.target||'ALL'} className={input}/></Field><Field label="Expires"><input name="expiresAt" type="date" defaultValue={edit?.expiresAt?.slice(0,10)||''} className={input}/></Field>{!edit&&<Field label="Attachment URL"><input name="attachmentUrl" type="url" className={input}/></Field>}<Field label="Urgent"><input type="checkbox" name="isUrgent" defaultChecked={edit?.isUrgent}/></Field><Field label="Notice body"><textarea name="body" defaultValue={edit?.body} required className={input}/></Field>{edit&&<button type="button" onClick={()=>setEdit(null)} className="px-3 py-2 text-sm">Cancel edit</button>}</Form></details></div>}
function Report({data}:any){return <div className="space-y-4"><h2 className="font-bold">Occupancy by block</h2><Table headers={['Block','Code','Total beds','Occupied','Available','Rate']} rows={(data.occupancyByBlock||[]).map((x:any)=>[x.name,x.code,x.totalBeds,x.occupiedBeds,x.availableBeds,`${x.occupancyRate}%`])}/><h2 className="font-bold">Fees</h2><Table headers={['Payment status','Amount','Count']} rows={(data.feeDistribution||[]).map((x:any)=>[x.name,money(x.value),x.count])}/><div className="grid gap-4 md:grid-cols-3"><pre className="rounded-xl bg-white p-4 text-xs">Applications{`\n`}{JSON.stringify(data.appStats,null,2)}</pre><pre className="rounded-xl bg-white p-4 text-xs">Outpasses{`\n`}{JSON.stringify(data.outpassStats,null,2)}</pre><pre className="rounded-xl bg-white p-4 text-xs">Visitors / curfew{`\n`}{JSON.stringify({visitors:data.visitorStats,curfew:data.curfewStats},null,2)}</pre></div></div>}
function AdminUsers({data,loading,error,reload,call,busy,searchBox,qRows}:any){const [newUserRole,setNewUserRole]=useState('STUDENT');return <div className="space-y-4"><details className="rounded-2xl border bg-white p-4"><summary className="cursor-pointer font-bold">Create account</summary><Form busy={busy} submit="Create user" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void call(()=>api.post('/admin/users',Object.fromEntries(f)),reload)}}>{[['name','Name'],['email','Email'],['password','Initial password']].map(([n,l])=><Field key={n} label={l}><input name={n} type={n==='password'?'password':'text'} minLength={n==='password'?6:undefined} required className={input}/></Field>)}<Field label="Role"><select name="role" value={newUserRole} onChange={e=>setNewUserRole(e.target.value)} className={input}>{['STUDENT','WARDEN','ACCOUNTS','SECURITY','ADMIN'].map(r=><option key={r}>{r}</option>)}</select></Field><Field label="Student roll (students only)"><input name="rollNumber" required={newUserRole==='STUDENT'} className={input}/></Field></Form></details>{searchBox}{!loading&&!error&&<Table headers={['Name','Email','Role','Status','Student','Actions']} rows={qRows(data||[]).map((u:any)=>[u.name,u.email,u.role,u.isActive?'Active':'Inactive',u.student?`${u.student.rollNumber} · ${u.student.course}`:'—',<>{actionBtn('Edit',()=>{const name=window.prompt('Update display name:',u.name);if(name!==null){const role=window.prompt('Role (STUDENT, WARDEN, ACCOUNTS, SECURITY, ADMIN):',u.role);if(role)void call(()=>api.put(`/admin/users/${u.id}`,{name,role:role.toUpperCase()}),reload)}})}{actionBtn(u.isActive?'Deactivate':'Activate',()=>call(()=>api.put(`/admin/users/${u.id}`,{isActive:!u.isActive}),reload))}{actionBtn('Reset password',()=>{const newPassword=window.prompt('Enter new password (at least 6 characters):');if(newPassword)void call(()=>api.post(`/admin/users/${u.id}/reset-password`,{newPassword}),reload)})}</>])}/>}</div>}
